version: '3.6'

services:
  database:
    container_name: postgres_marmitaz
    image: postgres:9.5
    environment:
      POSTGRES_USER: marmitaz
      POSTGRES_PASSWORD: z9FHfKG0O279
    ports:
      - "5432:5432"
